import { useEffect,useState } from 'react'
import { PageHead } from './PageHead'
import { supabase } from '../lib/supabase'

type Reward={id:number;name:string;description:string;icon:string;rarity:string;color:string;ticketsLeft:number}
export function Gacha(){const [item,setItem]=useState<Reward|null>(null);const [opening,setOpening]=useState(false);const [tickets,setTickets]=useState(0);const [error,setError]=useState('');
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data,error:e}=await supabase.from('profiles').select('tickets').eq('id',user.id).single();if(e)setError(e.message);setTickets(data?.tickets??0)})()},[])
 const pick=async()=>{if(opening||tickets<1)return;setOpening(true);setError('');try{const {data,error:e}=await supabase.rpc('open_gacha');if(e)throw e;setItem(data as Reward);setTickets(data.ticketsLeft)}catch(e){setError(e instanceof Error?e.message:'Não foi possível abrir o baú.')}finally{setOpening(false)}}
 return <section className="sc"><div className="scr-scroll"><PageHead title="Mystic Chest" sub="Test your luck. Claim a reward."/>{error&&<p className="form-error">{error}</p>}<button aria-label="Abrir baú" className={opening?'chest opening':'chest'} onClick={pick}>🎁</button><div className="gcur"><div>💎 <b>—</b><small>Gems</small></div><div>🎟️ <b>{tickets}</b><small>Tickets</small></div></div><button className="gold-btn" disabled={opening||tickets<1} onClick={pick}>{opening?'OPENING...':tickets<1?'NO TICKETS':'OPEN CHEST · 1 TICKET'}</button></div>{item&&<div className="modal"><div className="reveal-card"><div className="stars">✦ ✦ ✦</div><div className="rev-bg">{item.icon}</div><b style={{color:item.color}}>{item.rarity}</b><h2>{item.name}</h2><p>{item.description}</p><button onClick={()=>setItem(null)}>CONTINUAR</button></div></div>}</section>}
